server:
  port: 9091
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    context-path: /clm-api-authen

spring:
  application:
    name: clm-api-authen
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb-clm-01
    username: root
    password: nopass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
authentication:
  bypass:
    username:
    password:
  security:
    jwt:


